import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Dashboard from "./Dashboard/page";
import styles from "./layout.module.scss";
import "bootstrap/dist/css/bootstrap.min.css";
import Script from "next/script";
import DataForm from "../components/form/addData";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <meta charSet="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className={styles.parent}>
          <Dashboard />
          <div className={styles.modal} >
            <div className={styles.modalBtn}>
            <button
              type="button"
              className="btn btn-primary"
              data-bs-toggle="modal" // Assurez-vous d'utiliser data-bs-toggle pour Bootstrap 5
              data-bs-target="#exampleModal" // Assurez-vous d'utiliser data-bs-target pour Bootstrap 5
            >
              Add Data
            </button>
            </div>
            <div
              className="modal fade"
              id="exampleModal"
              tabIndex={-1}
              aria-labelledby="exampleModalLabel"
              aria-hidden="true"
            >
              <div className="modal-dialog">
                <div className="modal-content">
                  <div className="modal-header">
                    <button
                      type="button"
                      className="btn-close"
                      data-bs-dismiss="modal" // Assurez-vous d'utiliser data-bs-dismiss pour Bootstrap 5
                      aria-label="Close"
                    ></button>
                  </div>
                  <div className="modal-body">
                    <DataForm/>
                  </div>
                 
                </div>
              </div>
            </div>
            {children}
          </div>
        </div>
        <Script
          src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.5/dist/js/bootstrap.bundle.min.js"
          integrity="sha384-k6d4wzSIapyDyv1kpU366/PK5hCdSbCRGRCMv+eplOQJWyd1fbcAu9OCUj5zNLiq"
          crossOrigin="anonymous"
        />
      </body>
    </html>
  );
}
